config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users, :except => [:index, :edit] do
    member do
      get :all
      get :search
      get :account_password
      get :setting
      get :documents
      post :set_vnd
      post :remove_seller
      post :add_seller
      post :remove_manager
      patch :set_note
    end
    resources :orders do
      get :remove
      patch :set_received
      collection do
        get :look_up_order
        get :show_table
      end
    end
    resources :shippings do
      collection do
        get :quick_add
        post :update_quick_add
        get :lookup_range
        get :lookup_shipment
        get :all
      end
    end
    resources :customers
    resources :stores
    resources :data, :only => [:show]

    resources :requests do
      collection do
        patch :perform_request
        get :completed
      end
    end

    resources :messages

    get 'range_orders' => 'orders#look_up_range'
    get 'activities' => 'reports#activity_log'
    get 'report' => 'reports#show_report'
    post 'report' => 'reports#generate_report'
    get 'year' => 'reports#show_year'
    get 'months' => 'reports#monthly_index'

    get 'inbox' => 'inboxes#requests'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if current_user
      array_id = []
      array_id << current_user.id
      if current_user.role == "manager"
        array_id << current_user.seller.id if current_user.seller.present?
      else
        array_id << current_user.manager.id if current_user.manager.present?
      end
      @activities = PublicActivity::Activity.order("created_at desc").where(owner_id: array_id).limit(10).uniq
      @this_month = current_user.data.where("month_record BETWEEN ? AND ?", Time.now.beginning_of_month, Time.now.end_of_month).first
      @user = current_user
      @requests = current_user.requests.where(check: false).count
      @messages = current_user.messages.where("messages.user_id != ?", current_user.id).where(read: false).count
      unless @this_month.nil?
        completed = @this_month.orders.where.not("ship_vn" => nil).received.count
        total = @this_month.order_sold
        received = @this_month.orders.where("ship_vn" => nil).received.count

        @total_display = total
        @completed_display = completed
        @pending_display = received
        @remaining_display = total - completed - received

        @completed = ((completed.to_f / total) * 100)
        @received = ((received.to_f / total) * 100)
        @not_received = 100 - @completed - @received
      end
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def greeting_message
    current_time = Time.now.to_i
    midnight = Time.now.beginning_of_day.to_i
    noon = Time.now.middle_of_day.to_i
    five_pm = Time.now.change(:hour => 17 ).to_i
    eight_pm = Time.now.change(:hour => 20 ).to_i

    if midnight.upto(noon).include?(current_time)
      "Good morning"
    elsif noon.upto(five_pm).include?(current_time)
      "Good afternoon"
    elsif five_pm.upto(eight_pm).include?(current_time)
      "Good evening"
    elsif eight_pm.upto(midnight + 1.day).include?(current_time)
      "Good night"
    end
  end

  def display_name(name)
    if current_user.name == name
      "You"
    else
      name
    end
  end

end

app/views/static_pages/_front_page.html.erb
<div class="jumbotron">
<div class="container" style="padding-top: 80px; padding-bottom: 100px;">
  <h1>Welcome to Gotato!</h1>
  <h3 class="jumbo-text text-muted">Our online sales database</h3>
  
  <button class="btn btn-lg btn-danger button_div">
    <strong><%= link_to "Sign up now!", signup_path, class: "shipment_btn" %></strong>
  </button>
</div>
</div>

<legend></legend>
<div class="row" style="padding-top: 20px; padding-bottom: 25px;">
  <div class="col-xs-12 col-md-8 col-md-offset-2 text-center">
  	<p class="lead home-text">What is Gotato?</p>
  	<p class="lead">A powerful online database that helps online shopkeepers mange sales data.</p>
  	<p class="lead">Written exclusively for <%= link_to "Trendy Alley Shop", "https://www.facebook.com/trendy.alley", :target => "_blank" %>.</p>
  </div>
</div>

<legend></legend>
<div class="row" style="padding-top: 20px; padding-bottom: 30px;">
  <div class="col-xs-12 col-md-8 col-md-offset-2 text-center">
  	<p class="lead home-text">
  	  We want to end dependence on Excel.
  	</p>
    <p><i class="fa fa-spinner fa-spin fa-3x"></i></p>
    <p class="lead">
  	  For an online store with thousands of orders, keeping data on Excel can cause many problems:
  	</p>
    <p class="lead text-muted">
  	  <em>Sales productivity decreases as the number of records and users increase.</em>
  	</p>
  	<p class="lead text-muted">
  	  <em>Too many worksheets make it hard to visualize how data fits together.</em>
  	</p>
  	<p class="lead text-muted">
  	  <em>A hardware failure or virus can potentialy mess up the data files.</em>
  	</p>
    <p class="lead text-muted">
      <em>...</em>
    </p>
  </div>
</div>

<legend></legend>
<div class="row" style="padding-top: 20px; padding-bottom: 25px;">
  <div class="col-xs-12 col-md-8 col-md-offset-2 text-center">
  	<p class="lead home-text text-muted">
  	  Gotato was built to solve those problems.
  	</p>
  	<p class="lead home-text">How?</p>
  </div>
</div>


<legend></legend>
<div class="row" style="padding-top: 20px; padding-bottom: 30px;">
  <div class="col-xs-12 col-md-4 col-md-offset-2">
    <%= image_tag("placeit3.jpg", :alt => "graph", class: "image2") %>
  </div>
  <div class="col-xs-12 col-md-5">
  <h2>It is All-in-one</h2>
  <p class="lead" style="margin-top: 20px;">
    Gotato is not just a website for displaying spreadsheets. It's a system where our users: managers, suppliers and sellers work together, from saving/sharing data to communicate.
  </p>
  <p class="lead">
    We have a built-in instant messaging system. Want to discuss about sales? Let's have a chat right in here!
  </p>
  </div>
</div>

<legend></legend>
<div class="row" style="padding-top: 30px; padding-bottom: 30px;">
  <div class="col-xs-12 col-md-5 col-md-offset-2">
	<h2>Smart and Simple</h2>
  <p class="lead" style="margin-top: 20px;">
    Gotato automatically does all the heavy lifting for our users, from calculating data to generating sale reports. Gotato minimizes the hassle our users have to face daily in Excel.
  </p>
  <p class="lead" style="margin-top: 20px;">
    Users can view all information on the same page with spreadsheet-style interface.
  </p>
  </div>
  <div class="col-xs-12 col-md-4">
    <%= image_tag("placeit.png.jpg", :alt => "graph", class: "image") %>
  </div>
</div>


<legend></legend>
<div class="row" style="padding-top: 20px; padding-bottom: 30px;">
  <div class="col-xs-12 col-md-4 col-md-offset-2">
    <%= image_tag("placeit.png", :alt => "graph", class: "image2") %>
  </div>
  <div class="col-xs-12 col-md-5">
  <h2>Accessible</h2>
  <p class="lead" style="margin-top: 20px;">
    It is online. Our user, with a manager account, at the U.S. can work on the same data with a seller in VN seamlessly. All users can access the database anytime, anywhere.
  </p>
  <p class="lead">
    Built with Bootstrap, Gotato interface is respondsive, mobile friendly.
  </p>
  </div>
</div>

<legend></legend>
<div class="row" style="padding-top: 30px; padding-bottom: 30px;">
  <div class="col-xs-12 col-md-8 col-md-offset-2">
  <h2><i class="fa fa-lock"></i> Safe and Secure</h2>
  <p class="lead" style="margin-top: 20px;">
    Gotato secures the database with authentication check. Every user has their own account, a seller account can only access the database when get a permission from a manager.
  </p>
  <p class="lead">
    Different types of users have different types of permissions: A manager account can have full access to create and manage all resources, while a seller account have limited access and can only work with the manager's shared data.
  </p>
  </div>
</div>

<legend></legend>
<div class="row" style="padding-top: 40px; padding-bottom: 50px;">
  <div class="col-xs-12 col-md-8 col-md-offset-2 text-center">
  	<p class="lead home-text">
  	  Interested?
  	</p>
  	<p class="lead"><%= link_to "Check out the documentation", "https://github.com/LongPotato/Gotato", :target => "_blank" %></p>
  	<p class="lead">
  		This project is open source on <%= link_to "https://github.com/LongPotato/Gotato", class: "sort-header", :target => "_blank" do %>
            <i class="fa fa-github-square"></i> GitHub.
          <% end %>
        </li>
  	</p>
  </div>
</div>
<legend></legend>

app/views/static_pages/_note_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Note</h4>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_for(@user, url: set_note_user_path(current_user)) do |f| %>
          <%= f.text_area :note, label: "Enter reminder note" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Save", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <p class="text-center lead" style="font-size: 30px;"> <%= greeting_message %>, <%= current_user.name.titleize %> </p>

  <div class="row">

    <div class="col-md-3">
      <legend>Recent activities</legend>
      <div class="panel panel-default">
        <div class="panel-body">
          <% unless current_user.role == "seller" && current_user.manager.nil? %>
            <%= render_activities @activities %>
            <%= link_to "View activity log", user_activities_path(current_user) %>
          <% else %>
            <p class="text-center text-muted lead">You have no activity</p>
          <% end %>
        </div>
      </div>
    </div>


    <div class="col-md-6">

      <legend>Today</legend>
      <div class="panel panel-default">
      <div class="panel-body">

        <div class="row">
          <div class="col-md-6">
            <p style="font-size: 16px;">
              <i class="fa fa-usd"></i> <strong>Exchange rate:</strong><span class="tab-space"></span><%= number_with_delimiter(current_user.setting_vnd.floor, :delimiter => ',') %> VND
            </p>
          </div>

          <div class="col-md-6 text-center">
            <p style="font-size: 16px;"><%= Time.now.strftime("%m/%d/%Y") %></p>
          </div>
        </div>

        <div class="row refresh">
          <div class="col-md-12">
            <% if current_user.note.nil? || current_user.note.try(:empty?) %>
              <button type="button" class="btn btn-small btn-default" data-toggle="modal" data-target="#myModal"><strong><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Create note</strong></button>
            <% else %>
              <p style="font-size: 16px;">
                <strong><%= link_to "", {'data-toggle' => "modal", 'data-target' => "#myModal"} do %>
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                  <% end %> Note: </strong><span class="tab-space"></span><%= current_user.note %>
              </p>
            <% end %>
          </div>
        </div>

      </div>
      </div>

      <legend class="field">This month - <%= Time.now.strftime("%B, %Y") %></legend>
      <div class="panel panel-default">
      <div class="panel-body">

        <div class="row" style="margin-top: 20px;">
          <div class="col-md-12">

          <% if @this_month.nil? || @this_month.try(:orders).empty? %>
            <p class="text-center text-muted lead">No order</p>
            <% if current_user.role == "seller" && current_user.manager.nil? %>
              <p class="text-center text-muted lead">You have no associate manager. Link your account with a manager to start managing the database.</p>
            <% end %>
          <% else %>
            <div class="progress">
              <div class="progress-bar progress-bar-success" style="width: <%= @completed %>%">
                Completed
              </div>
              <div class="progress-bar progress-bar-warning progress-bar-striped" style="width: <%= @received %>%">
                Pending
              </div>
              <div class="progress-bar progress-bar-danger" style="width: <%= @not_received %>%">
                Remaining
              </div>
            </div>
          <% end %>

          <table class="table" style="margin-top: 30px; font-size: 15px; border-bottom: 1px solid #eaeaea;">
          <tbody>
            <tr>
              <td><b>Orders:</b></td>
              <td></td>
              <td style="text-align: center;"><%= @total_display %></td>
            </tr>
            <tr>
              <td><b>Completed:</b></td>
              <td></td>
              <td style="text-align: center;"><%= @completed_display %></td>
            </tr>
            <tr>
              <td><b>Pending:</b></td>
              <td></td>
              <td style="text-align: center;"><%= @pending_display %></td>
            </tr>
            <tr>
              <td><b>Remaining:</b></td>
              <td></td>
              <td style="text-align: center;"><%= @remaining_display %></td>
            </tr>
          </tbody>
          </table>

          <%= link_to "View this month's report", user_report_path(current_user), method: :post %>

          </div>
        </div>

      </div>
      </div>

    </div>


    <div class="col-md-3">

      <legend>My account</legend>
      <div class="panel panel-default">
        <div class="panel-body">

        <div class="row" style="font-size: 16px;">
        <div class="col-md-6">

          <p>
            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
            <%= pluralize(current_user.orders.count, "order") %>
          </p>
          <p>
            <span class="glyphicon glyphicon-plane" aria-hidden="true"></span>
            <%= pluralize(current_user.shippings.uniq.count, "shipment") %>
          </p>
          <p>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            <%= pluralize(current_user.customers.count, "customer") %>
          </p>

        </div>

        <div class="col-md-6">
          <p>Account type: <%= current_user.role.capitalize %></p>

          <% if current_user.role == "manager" %>
            <% if current_user.seller.present? %>
              <p>Seller: <%= current_user.seller.name.titleize %></p>
            <% else %>
              <p>No seller</p>
            <% end %>
          <% else %>
            <% if current_user.manager.present? %>
              <p>Manager: <%= current_user.manager.name.titleize %></p>
            <% else %>
              <p>No manager</p>
            <% end %>
          <% end %>
        </div>
        </div>

        <legend></legend>
        <%= link_to "View my account", user_path(current_user) %>

        </div>
      </div>

    </div>

    <div class="col-md-3">
      <legend>Inside inbox</legend>

      <div class="list-group">
        <button type="button" class="list-group-item" style="font-size: 16px;">
          <%= link_to user_inbox_path(current_user), class: "sort-header", style: "color: black;", method: :get do %>
            Order requests <span class="badge pull-right"><%= @requests %></span>
          <% end %>
        </button>
        <button type="button" class="list-group-item" style="font-size: 16px;">
          <%= link_to user_messages_path(current_user), class: "sort-header", style: "color: black;", method: :get do %>
            New messages <span class="badge pull-right"><%= @messages %></span>
          <% end %>
        </button>
      </div>

    </div>


  </div>

  <%= render 'note_modal' %>

<% else %>
  <%= render 'front_page' %>
<% end %>