config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users, :except => [:index, :edit] do
    member do
      get :all
      get :search
      get :account_password
      get :setting
      get :documents
      post :set_vnd
      post :remove_seller
      post :add_seller
      post :remove_manager
      patch :set_note
    end
    resources :orders do
      get :remove
      patch :set_received
      collection do
        get :look_up_order
        get :show_table
      end
    end
    resources :shippings do
      collection do
        get :quick_add
        post :update_quick_add
        get :lookup_range
        get :lookup_shipment
        get :all
      end
    end
    resources :customers
    resources :stores
    resources :data, :only => [:show]

    resources :requests do
      collection do
        patch :perform_request
        get :completed
      end
    end

    resources :messages

    get 'range_orders' => 'orders#look_up_range'
    get 'activities' => 'reports#activity_log'
    get 'report' => 'reports#show_report'
    post 'report' => 'reports#generate_report'
    get 'year' => 'reports#show_year'
    get 'months' => 'reports#monthly_index'

    get 'inbox' => 'inboxes#requests'
  end

end

app/models/store.rb
class Store < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: Proc.new { |controller, model| controller.current_user ? controller.current_user : nil }

  has_and_belongs_to_many :users
  has_many :orders

  before_save { self.name = name.try(:downcase).try(:strip) }

  #get next available order
  def next
    order = self.class.includes(:users).where("id > ?", id).first
    if order
      order
    else
      self.class.first
    end
  end

  #get previous order
  def prev
    order = self.class.includes(:users).where("id < ?", id).first
    if order
      order
    else
      self.class.last
    end
  end

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search.downcase}%")
    else
      all
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user

  def index
    @stores = current_user.stores.search(params[:search]).uniq.order("name asc")
  end

  def show
    @store = current_user.stores.find(params[:id])
    @orders = @store.orders.order("id desc").last(8)
  end

  def edit
    @store = current_user.stores.find(params[:id])
    @user = current_user
  end

  def update
    @store = current_user.stores.find(params[:id])
    if @store.update_attributes(store_params)
      flash[:success] = "Updated info for #{@store.name.titleize}."
      redirect_to user_store_path(current_user, @store.id)
    else
      render 'edit'
    end
  end

  private
  
    def store_params
      params.require(:store).permit(:note)
    end


end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/edit.html.erb
<% provide(:title, "Edit Store Info") %>

<h1>Store Info</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">

  <%= bootstrap_form_for([@user, @store]) do |f| %>

    <legend class="field"></legend>

    <p class="p_order"><b>Store name:</b><span class="tab-space">
      <%= @store.name.try(:titleize) %>
    </p>

    <legend class="field"></legend>

    <%= f.text_area :note %>

    <legend class="field"></legend>

    <%= f.submit "Submit", class: "btn btn-lg btn-info" %>

    <%= link_to "Cancel", :back, class: "btn btn-lg btn-default" %>
  <% end %>
 </div>
</div>

app/views/stores/index.html.erb
<% provide(:title, 'Stores') %>

<div class="row">
 <div class="col-md-10 col-md-offset-1">

  <div class="row">
  <div class="col-lg-6">

    <form accept-charset="UTF-8" action="/users/<%= current_user.id %>/stores" method="get" id="customers_search">
      <div class="input-group">
        <span class="input-group-btn">
          <button type="button" class="btn btn-default">
           <span aria-hidden="true" class="order_btn">&larr;</span> <%= link_to "Back", :back, class: "order_btn" %>
          </button>
        </span>
        <input type="text" class="form-control" placeholder="Search store..." name="search">
        <span class="input-group-btn">
          <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search</button>
        </span>
      </div>
    </form>

  </div>
  </div>

<table class="table table-hover table-align customer-table">
  <thead>
    <tr>
      <th width="200">Name</th>
      <th width="300">Note</th>
      <th width="150">Number of Orders</th>
      <th width="150">Action</th>
    </tr>
    </thead>

    <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name.try(:titleize) %></td>

        <td><%= store.note %></td>

        <td><%= store.orders.count %></td>
        <td><%= link_to "View detail", user_store_path(current_user, store.id) %></td>
      </tr>
    <% end %>
    </tbody>
</table>

</div>
</div>

app/views/stores/show.html.erb
<%= provide(:title, 'Store Profile') %>

<div class="row nav-show">
<nav id="back_next">
  <ul class="pager">
    <li class="previous"><%= link_to raw('<span aria-hidden="true">&larr;</span> Previous'), 
                             user_store_path(current_user, @store.prev), class: "order_btn" %>
    </li>
    <li class="next"><%= link_to raw('Next <span aria-hidden="true">&rarr;</span>'),
                         user_store_path(current_user, @store.next), class: "order_btn" %>
    </li>
  </ul>
</nav>
<h1>Store Profile</h1>
</div>

<div class="row">
 <div class="col-md-6 col-md-offset-3">

 <fieldset class="field">
   <legend></legend>

   <p class="p_order"><b>Store name:</b><span class="tab-space">
    <%= @store.name.try(:titleize) %>
   </p>

   <legend class="field"></legend>

   <p class="p_order"><b>Note:</b><span class="tab-space">
    <address><%= @store.note %></address>
   </p>

   <legend class="field"></legend>

   <p class="p_order"><b>Number of Orders:</b><span class="tab-space"><%= @store.orders.count %></p>

   <legend class="field">Recent orders:</legend>

  </div>

  <%= render 'orders/order_table' %>

  <div class="col-md-6 col-md-offset-3">

  <% if @store.orders.count > 8 %>
    <div class="text-center" style="font-size: 18px;"><%= link_to "View all orders >>", show_table_user_orders_path(current_user, :store => true, :store_id => @store.id), target: "_blank" %></div>
  <% end %>

  <legend class="field"></legend>

  <%= link_to "Edit Info", edit_user_store_path(current_user,@store.id), class: "btn btn-lg btn-info" %>
  <%= link_to "Cancel", :back, class: "btn btn-lg btn-default pull-right", method: :get %>

  </div>
  
 </fieldset>
</div>