config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users, :except => [:index, :edit] do
    member do
      get :all
      get :search
      get :account_password
      get :setting
      get :documents
      post :set_vnd
      post :remove_seller
      post :add_seller
      post :remove_manager
      patch :set_note
    end
    resources :orders do
      get :remove
      patch :set_received
      collection do
        get :look_up_order
        get :show_table
      end
    end
    resources :shippings do
      collection do
        get :quick_add
        post :update_quick_add
        get :lookup_range
        get :lookup_shipment
        get :all
      end
    end
    resources :customers
    resources :stores
    resources :data, :only => [:show]

    resources :requests do
      collection do
        patch :perform_request
        get :completed
      end
    end

    resources :messages

    get 'range_orders' => 'orders#look_up_range'
    get 'activities' => 'reports#activity_log'
    get 'report' => 'reports#show_report'
    post 'report' => 'reports#generate_report'
    get 'year' => 'reports#show_year'
    get 'months' => 'reports#monthly_index'

    get 'inbox' => 'inboxes#requests'
  end

end

app/models/request.rb
class Request < ActiveRecord::Base
  include PublicActivity::Model
  tracked except: [:update], owner: Proc.new { |controller, model| controller.current_user ? controller.current_user : nil }
  
  has_and_belongs_to_many :users

  before_save { self.check = false if self.check.nil? }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :reset_token

  #Attributes validations:
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_secure_password

  has_one :seller, class_name: "User", foreign_key: :manager_id
  belongs_to :manager, class_name: "User", foreign_key: :manager_id

  scope :manager, -> { where('role == ?', 'manager') }

  #Callback:
  before_save { self.email = email.downcase }
  before_save { self.setting_vnd = 21000 if self.setting_vnd.nil? }

  ROLES = %w[manager seller]

  #Relation:
  has_and_belongs_to_many :orders
  has_and_belongs_to_many :stores
  has_and_belongs_to_many :customers
  has_and_belongs_to_many :shippings
  has_and_belongs_to_many :data
  has_and_belongs_to_many :requests
  #has_many :messages, ->(user) {where("messages.sender_id = ? OR messages.recipient_id = ?", user.id, user.id)}
  has_and_belongs_to_many :messages

  #Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #Returns the hash digest of the given string.
  def User.encrypt_token(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.encrypt_token(reset_token))
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  #Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.encrypt_token(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def clear_reset_digest
    update_attribute(:reset_digest, nil)
  end

  def User.update_rate
    User.all.each {|user| user.update_vnd }
  end

  def update_vnd
    self.setting_vnd = GoogCurrency.usd_to_vnd(1)
    self.save!
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :logged_in_user

  def completed
    @requests = current_user.requests.where(check: true).order("id desc").paginate(:page => params[:page], :per_page => 6)
    @pending = current_user.requests.where(check: false).count
    @messages = current_user.messages.where("messages.user_id != ?", current_user.id).where(read: false)
  end

  def create
    @request = Request.create(url: params[:url], note: params[:note])

    @request.users << current_user unless @request.users.find_by_id(current_user.id)

    #Add users to request
    if current_user.role == "manager"
      if current_user.seller.present?
        @request.users << current_user.seller unless @request.users.find_by_id(current_user.seller.id)
      end
    else
      if current_user.manager.present?
        @request.users << current_user.manager unless @request.users.find_by_id(current_user.manager.id)
      end
    end

    if @request.save
      redirect_to user_inbox_path(current_user)
    else
      flash[:danger] = "Unable to create request."
      redirect_to user_inbox_path(current_user)
    end
  end

  def perform_request
    if params[:request_ids]
      if params[:commit] == "Mark as Completed"
        ids = params[:request_ids]
        ids.each do |id|
          @request = Request.find(id.to_i)
          @request.update_attributes(check: true)
          @request.create_activity :update, owner: current_user
        end
        redirect_to user_inbox_path(current_user)
      elsif params[:commit] == "Mark as not Completed"
        ids = params[:request_ids]
        ids.each do |id|
          @request = Request.find(id.to_i)
          @request.update_attributes(check: false)
          @request.create_activity :uncheck, owner: current_user
        end
        redirect_to completed_user_requests_path(current_user)
      elsif params[:commit] == "Delete"
        url = Rails.application.routes.recognize_path(request.referrer)  #Convert the previous url into a hash of controller and action
        store_location
        Request.destroy(params[:request_ids])
        redirect_back_or(user_inbox_path(current_user), url[:controller], url[:action])
      end
    else
      flash[:danger] = "Select at least one request to perform the action."
      redirect_to user_inbox_path(current_user)
    end
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    flash[:danger] = "Request deleted."
    redirect_to user_inbox_path(current_user)
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/completed.html.erb
<% provide(:title, 'Inbox | Request') %>
<%= content_for(:body_attributes) do %> data-no-turbolink <% end %>

<div class="row">
<div class="col-md-10 col-md-offset-1">

  <div class="row">
	<div class="col-md-2" style="margin-top: 60px;">
	  <ul class="nav nav-pills nav-stacked">
		 <li role="presentation" class="active">
		 	<a href="<%= user_inbox_path(current_user) %>"><b>Requests</b>
		 		<% unless @pending == 0 %><span class="badge pull-right"><%= @pending %></span><% end %>
		 	</a>
		 </li>
		 <li role="presentation">
		 	<a href="<%= user_messages_path(current_user) %>"><b>Messages</b>
		 		<% unless @messages.count == 0 %><span class="badge pull-right"><%= @messages.count %></span><% end %>
		 	</a>
		 </li>
	  </ul>
	</div>

	<div class="col-md-10">
      <ul class="nav nav-tabs nav-justified">
	    <li role="presentation">
	    	<%= link_to "Pending", user_inbox_path(current_user), class: "customer" , method: :get %>
	    </li>
	    <li role="presentation" class="active"><a href="<%= completed_user_requests_path(current_user) %>" class="customer" method="get"><b>Completed</b></a></li>
      </ul>
      
      <div class="row nav-order" style="margin-top: 20px;">
      	<% if can? :create, Request %>
        <button class="btn btn-default" type="none" data-toggle="modal" data-target="#exampleModal"><i class="fa fa-plus"></i> Request</button>
        <% end %>
<%= form_tag perform_request_user_requests_path(current_user), :method => :patch, style: "display: inline;" do %>
        <% if can? :update, Request %>
        <%= submit_tag "Mark as not Completed", class: "btn btn-default" %>
        <% end %>
        <% if can? :destroy, Request %>
        <%= submit_tag "Delete", class: "btn btn-default" %>
        <% end %>
      </div>

    <div class="row">
    <div class="col-md-10 col-md-offset-1" style="margin-top: 20px;">
    <% unless @requests.empty? %>
      <% @requests.each do |request| %>

	    <div class="panel panel-default">
	    <div class="panel-heading"> 
		  <span class="text-muted">
		  <%= check_box_tag "request_ids[]", request.id %>
		  <p class="pull-right">
		  <% if current_user.seller.present? %>
		    <%= current_user.seller.name.titleize %> - 
		  <% else %>
		    You - 
		  <% end %>
		  <%= request.created_at.strftime('%H:%M %m/%d/%Y') %>
	      </p><br>
		  </span>
		</div>
	    <div class="panel-body">
          <a href="<%= request.try(:url) %>" target="_blank"><%= request.try(:url) %></a><br>
          <%= request.try(:note) %>
	    </div>
	    </div>

	    <% end %>
	<% else %>
	  <p class="lead text-muted text-center">No request</p>
	<% end %>
	</div>
    </div>

    <%= will_paginate @requests, renderer: BootstrapPagination::Rails %>
    
	</div>
  </div>

</div>
</div>

<% end %>

<%= render 'inboxes/request_modal' %>