config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users, :except => [:index, :edit] do
    member do
      get :all
      get :search
      get :account_password
      get :setting
      get :documents
      post :set_vnd
      post :remove_seller
      post :add_seller
      post :remove_manager
      patch :set_note
    end
    resources :orders do
      get :remove
      patch :set_received
      collection do
        get :look_up_order
        get :show_table
      end
    end
    resources :shippings do
      collection do
        get :quick_add
        post :update_quick_add
        get :lookup_range
        get :lookup_shipment
        get :all
      end
    end
    resources :customers
    resources :stores
    resources :data, :only => [:show]

    resources :requests do
      collection do
        patch :perform_request
        get :completed
      end
    end

    resources :messages

    get 'range_orders' => 'orders#look_up_range'
    get 'activities' => 'reports#activity_log'
    get 'report' => 'reports#show_report'
    post 'report' => 'reports#generate_report'
    get 'year' => 'reports#show_year'
    get 'months' => 'reports#monthly_index'

    get 'inbox' => 'inboxes#requests'
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user

  def show_report
    @this_month = current_user.data.where("month_record BETWEEN ? AND ?", Time.now.beginning_of_month, Time.now.end_of_month).first
    @shipment = current_user.shippings.where("ship_date BETWEEN ? AND ?", Time.now.beginning_of_month, Time.now.end_of_month).uniq
    unless @this_month.nil?
      @received = @this_month.orders.received.count
      @for_sale = @this_month.orders.joins(:customer).sale.count
      @shipped = @this_month.orders.where.not("ship_vn" => nil).count
      @total_shipping = @shipment.map(&:price).sum.to_f unless @shipment.nil?
      @total_reward = @this_month.orders.map(&:reward).sum.to_f

      @order_sold = @this_month.order_sold
      @revenue = @this_month.revenue.to_f.round
      @total_selling = @this_month.total_selling.to_f
      @total_cost = @this_month.total_cost.to_f
    else
      @revenue = 0
      @total_selling = 0
      @total_cost = 0
    end
  end

  def monthly_index
    @reports = current_user.data.order("month_record desc").uniq
  end

  def show_year
    @this_year = current_user.data.where("month_record BETWEEN ? AND ?", Time.now.beginning_of_year, Time.now.end_of_year).uniq.order("month_record desc")
    @shipment = current_user.shippings.where("ship_date BETWEEN ? AND ?", Time.now.beginning_of_year, Time.now.end_of_year).uniq
    unless @this_year.nil?
      @reports = @this_year
      @total_cost = @this_year.map(&:total_cost).sum.to_f.round(2)
      @total_selling = @this_year.map(&:total_selling).sum.to_f.round(2)
      @profit = (@total_selling - @total_cost).round(2)
      orders = get_batch_orders(@this_year)
      @total_shipping = @shipment.map(&:price).sum.to_f.round(2) unless @shipment.nil?
      @total_reward = orders.map(&:reward).sum.to_f.round(2)
    end
  end

  def generate_report
    @orders_by_month = current_user.orders.all.group_by { |order| order.order_date.beginning_of_month }
    
    @orders_by_month.each do |month, orders|
      if current_user.data.where("extract(year from month_record) = ?", month.strftime('%Y').to_i).present?
        this_year = current_user.data.where("extract(year from month_record) = ?", month.strftime('%Y').to_i)
        if this_year.where("extract(month from month_record) = ?", month.strftime('%m').to_i).present?
          @report = this_year.where("extract(month from month_record) = ?", month.strftime('%m').to_i).first
        else
          @report = Datum.new
        end
      else
        @report = Datum.new
      end
      vnd = orders.first.vnd.to_f
      total_cost = (orders.map(&:total_cost).sum.to_f / vnd).round(2)
      selling = (orders.map(&:selling_price).sum.to_f / vnd).round(2)
      count = orders.count

      @report.month_record = month
      @report.total_cost = total_cost
      @report.total_selling = selling
      @report.revenue = (selling - total_cost).round(2)
      @report.order_sold = count
      @report.users << current_user unless @report.users.find_by_id(current_user.id)

      if current_user.role == "manager"
        if current_user.seller.present?
          @report.users << current_user.seller unless @report.users.find_by_id(current_user.seller.id)
        end
      else
        if current_user.manager.present?
          @report.users << current_user.manager unless @report.users.find_by_id(current_user.manager.id)
        end
      end

      @report.save

      orders.each do |order|
        order.update_attributes(datum_id: @report.id)
      end

      check_valid_data
    end

    redirect_to user_report_path(current_user)
  end

  def activity_log
    @main_user = PublicActivity::Activity.order("created_at desc").where(owner_id: current_user.id).limit(50).uniq.paginate(:page => params[:user_page], :per_page => 6)
    if current_user.role == "manager" && current_user.seller.present?
      @linked_user = PublicActivity::Activity.order("created_at desc").where(owner_id: current_user.seller.id).limit(50).uniq.paginate(:page => params[:link_page], :per_page => 6)
    elsif current_user.role == "seller" && current_user.manager.present?
      @linked_user = PublicActivity::Activity.order("created_at desc").where(owner_id: current_user.manager.id).limit(50).uniq.paginate(:page => params[:link_page], :per_page => 6)
    else
      @linked_user = []
    end
  end

  private

    def check_valid_data
      data = current_user.data
      data.each do |datum|
        if datum.orders.empty?
          datum.destroy
        end
      end
    end

    def get_batch_orders(this_year)
      orders = []
      this_year.each do |datum|
        orders << datum.orders
      end
      return orders.flatten
    end

end

app/helpers/reports_helper.rb
module ReportsHelper

  def generate_chart_profit(this_year)
    graph_data = Hash.new(0)
    this_year.each do |data|
      graph_data[data.month_record] = data.revenue.to_f
    end
    return graph_data
  end

  def generate_chart_cost(this_year)
    graph_data = Hash.new(0)
    this_year.each do |data|
      graph_data[data.month_record] = data.total_cost.to_f
    end
    return graph_data
  end

  def generate_chart_selling(this_year)
    graph_data = Hash.new(0)
    this_year.each do |data|
      graph_data[data.month_record] = data.total_selling.to_f
    end
    return graph_data
  end

end

app/views/reports/_months_table.html.erb
<table class="table table-hover table-align customer-table">
  <thead>
    <tr>
      <th width="50">Months</th>
      <th width="50">Orders Sold</th>
      <th width="100">Total Cost</th>
      <th width="100">Total Selling</th>
      <th width="100">Profit</th>
    </tr>
    </thead>

  <tbody>
    <% @reports.each do |report| %>
    <tr>
      <td>
        <%= link_to "#{report.month_record.try(:strftime, "%B, %Y")}", user_datum_path(current_user, report), class: "customer", method: :get %>
      </td>
      <td><%= report.order_sold %></td>
      <td>$ <%= number_with_delimiter(report.total_cost.to_f, :delimiter => ',') %></td>
      <td>$ <%= number_with_delimiter(report.total_selling.to_f, :delimiter => ',') %></td>
      <td>$ <%= number_with_delimiter(report.revenue.to_f, :delimiter => ',') %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/activity_log.html.erb
<% provide(:title, 'Activity Log') %>

<div class="row">
<div class="col-md-10 col-md-offset-1">
  <ul class="nav nav-tabs">
    <li role="presentation">
      <%= link_to "This month", user_report_path(current_user), class: "customer", method: :post %>
    </li>
    <li role="presentation">
      <%= link_to user_year_path(current_user), class: "customer" do %>
        <i class="fa fa-line-chart"></i> This year
      <% end %>
    </li>
    <li role="presentation">
      <%= link_to user_months_path(current_user), class: "customer" do %>
        <i class="fa fa-list"></i> Monthly Index
      <% end %>
    </li>
    <li role="presentation" class="active">
      <%= link_to user_activities_path(current_user), class: "customer" do %>
        <i class="fa fa-rss"></i> Activity Log
      <% end %>
    </li>
  </ul>
</div>
</div>

<div class="row">

  <div class="col-md-5 col-md-offset-1">
    <legend class="sale-info">My activities:</legend>

    <% unless @main_user.empty? %>
      <div class="panel panel-default">
      <div class="panel-body">
        <%= render_activities @main_user %>
        <%= will_paginate @main_user, :param_name => 'user_page', renderer: BootstrapPagination::Rails %>
      </div>
      </div>
    <% else %>
      <p class="lead text-muted text-center sale-info">No activity.</p>
    <% end %>
  </div>

  <div class="col-md-5">
    <% if current_user.role == "manager" && current_user.seller.present? %>
      <legend class="sale-info">My seller's activities:</legend>
    <% elsif current_user.role == "seller" && current_user.manager.present? %>
      <legend class="sale-info">My manager's activities:</legend>
    <% else %>
      <legend class="sale-info">Associate's activities:</legend>
    <% end %>

    <% unless @linked_user.empty? %>
      <div class="panel panel-default">
      <div class="panel-body">
        <%= render_activities @linked_user %>
        <%= will_paginate @linked_user, :param_name => 'link_page', renderer: BootstrapPagination::Rails %>
      </div>
      </div>
    <% else %>
      <p class="lead text-muted text-center sale-info">No associate account.</p>
    <% end %>
  </div>

</div>

app/views/reports/monthly_index.html.erb
<% provide(:title, 'Monthly Reports') %>

<div class="row">
<div class="col-md-10 col-md-offset-1">
  <ul class="nav nav-tabs">
    <li role="presentation">
      <%= link_to "This month", user_report_path(current_user), class: "customer", method: :post %>
    </li>
    <li role="presentation">
      <%= link_to user_year_path(current_user), class: "customer" do %>
        <i class="fa fa-line-chart"></i> This year
      <% end %>
    </li>
    <li role="presentation" class="active">
      <%= link_to user_months_path(current_user), class: "customer" do %>
        <i class="fa fa-list"></i> Monthly Index
      <% end %>
    </li>
    <li role="presentation">
      <%= link_to user_activities_path(current_user), class: "customer" do %>
        <i class="fa fa-rss"></i> Activity Log
      <% end %>
    </li>
  </ul>
</div>
</div>

<div class="row">
<div class="col-md-10 col-md-offset-1">

  <%= render "months_table" %>

</div>
</div>

<!--
<div class="row">
<div class="col-md-10 col-md-offset-1">
  <button type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
    <%= link_to "Refresh", user_report_path(current_user), class: "sort-header", method: :post %>
  </button>
</div>
</div>
-->

app/views/reports/show_report.html.erb
<% provide(:title, 'Sale Reports') %>

<div class="page">
<div class="row">
<div class="col-md-10 col-md-offset-1">
  <ul class="nav nav-tabs">
    <li role="presentation" class="active">
      <%= link_to "This month", user_report_path(current_user), class: "customer", method: :post %>
    </li>
    <li role="presentation">
      <%= link_to user_year_path(current_user), class: "customer" do %>
        <i class="fa fa-line-chart"></i> This year
      <% end %>
    </li>
    <li role="presentation">
      <%= link_to user_months_path(current_user), class: "customer" do %>
        <i class="fa fa-list"></i> Monthly Index
      <% end %>
    </li>
    <li role="presentation">
      <%= link_to user_activities_path(current_user), class: "customer" do %>
        <i class="fa fa-rss"></i> Activity Log
      <% end %>
    </li>
  </ul>
</div>
</div>

<div class="row">
<div class="col-md-8 col-md-offset-2">
  <legend class="sale-info">
    <h2>This month <p class="pull-right text-muted"><%= Time.now.strftime("%B, %Y") %></p></h2>
  </legend>
  <table class="table table-align">
    <thead>
    <tr class="active">
      <th width ="150">Orders</th>
      <th width ="150">Profit</th>
    </tr>
    </thead>

    <tbody>
    <tr style="border-bottom: 1px solid #eaeaea">
      <td style="font-size: 30px"><%= @order_sold %></td>
      <td style="font-size: 30px">$ <%= number_with_delimiter(@revenue, :delimiter => ',') %></td>
    </tr>
    </tbody>
  </table>

  <h3 class="sale-info">Sales summary</h3>

  <table class="table">
  <tbody class="p_order">
    <tr>
    <td><b>Total revenue:</b></td>
    <td></td>
    <td width="300">$ <%= number_with_delimiter(@total_selling, :delimiter => ',') %></td>
  </tr>
  <tr>
    <td><b>Total expenses:</b></td>
    <td></td>
    <td>$ <%= number_with_delimiter(@total_cost, :delimiter => ',') %></td>
  </tr>
  <tr style="border-bottom: 1px solid #eaeaea">
    <td></td>
    <td><b>Profit:</b></td>
    <td><b>$ <%= number_with_delimiter(@revenue, :delimiter => ',') %></b></td>
  </tr>
  </tbody>
  </table>

  <table class="table">
  <tbody class="p_order">
  <tr>
    <td style="border-top: none"><b>Total shipments:</b></td>
    <td style="border-top: none"></td>
    <td style="border-top: none"  width="300"><%= @shipment.count %></td>
  </tr>
  <tr>
    <td><b>Total shipping VN cost:</b></td>
    <td></td>
    <td>$ <%= number_with_delimiter(@total_shipping.to_f, :delimiter => ',') %></td>
  </tr>
  <tr>
    <td><b>Total rewards:</b></td>
    <td></td>
    <td>$ <%= number_with_delimiter(@total_reward.to_f, :delimiter => ',') %></td>
  </tr>
  </tbody>
  </table>


  <h3 class="sale-info">Order statuses</h3>
  <table class="table">
  <tbody class="p_order">
  <tr>
    <td><b>Received at US:</b></td>
    <td></td>
    <td width="300"><%= @received %> / <%= @order_sold %></td>
  </tr>
    <tr>
    <td><b>Shipped to VN (Completed):</b></td>
    <td></td>
    <td><%= @shipped %> / <%= @order_sold %></td>
  </tr>
  <tr>
    <td><b>For sale:</b></td>
    <td></td>
    <td><%= @for_sale %></td>
  </tr>
  </tbody>
  </table>

</div>
</div>
</div>

<div class="modal fade" id="loadingModal" data-backdrop="static" data-keyboard="false">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h3>
        <span class="glyphicon glyphicon-time">
        </span> Please Wait...
      </h3>
    </div>
    <div class="modal-body">
      <div class="progress">
        <div class="progress-bar progress-bar-striped active" role="progressbar" style="width: 100%">
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<script>
  //$('#loadingModal').modal('show');
  //CallServerFunction();
</script>

app/views/reports/show_year.html.erb
<% provide(:title, "#{Time.now.strftime("%Y")} Sales Report") %>

<div class="row">
<div class="col-md-10 col-md-offset-1">
  <ul class="nav nav-tabs">
    <li role="presentation">
      <%= link_to "This month", user_report_path(current_user), class: "customer", method: :post %>
    </li>
    <li role="presentation" class="active">
      <%= link_to user_year_path(current_user), class: "customer" do %>
        <i class="fa fa-line-chart"></i> This year
      <% end %>
    </li>
    <li role="presentation">
      <%= link_to user_months_path(current_user), class: "customer" do %>
        <i class="fa fa-list"></i> Monthly Index
      <% end %>
    </li>
    <li role="presentation">
      <%= link_to user_activities_path(current_user), class: "customer" do %>
        <i class="fa fa-rss"></i> Activity Log
      <% end %>
    </li>
  </ul>
</div>
</div>

<div class="row">
<div class="col-md-10 col-md-offset-1">
  <p class="sale-info lead"><%= Time.now.strftime("%Y") %> Overview</p>
  <%= line_chart(
      [ {name: "Total selling", data: generate_chart_selling(@this_year)},
      	{name: "Total cost", data: generate_chart_cost(@this_year)},
      	{name: "Profit", data: generate_chart_profit(@this_year)} ],
      	library: {title: "Sales Report"})
  %>

  <legend><p class="sale-info lead">Total Sales</p></legend>
  <table class="table">
  <tbody class="p_order">
    <tr>
    <td width="50" style="border-top: none"></td>
    <td style="border-top: none"><b>Total revenue:</b></td>
    <td style="border-top: none"></td>
    <td style="border-top: none">$ <%= number_with_delimiter(@total_selling, :delimiter => ',') %></td>
  </tr>
  <tr>
  	<td></td>
    <td><b>Total expenses:</b></td>
    <td></td>
    <td>$ <%= number_with_delimiter(@total_cost, :delimiter => ',') %></td>
  </tr>
  <tr>
  	<td></td>
    <td></td>
    <td width="300"><b>Total profit:</b></td>
    <td><b>$ <%= number_with_delimiter(@profit, :delimiter => ',') %></b></td>
  </tr>
  </tbody>
  </table>

  <table class="table">
  <tbody class="p_order">
  <tr>
  	<td width="50" style="border-top: none"></td>
    <td style="border-top: none"><b>Total shipments:</b></td>
    <td style="border-top: none"></td>
    <td style="border-top: none"><%= @shipment.count %></td>
  </tr>
  <tr>
    <td></td>
    <td><b>Total shipping VN cost:</b></td>
    <td></td>
    <td>$ <%= number_with_delimiter(@total_shipping, :delimiter => ',') %></td>
  </tr>
  <tr>
  	<td></td>
    <td><b>Total rewards:</b></td>
    <td></td>
    <td>$ <%= number_with_delimiter(@total_reward, :delimiter => ',') %></td>
  </tr>
  </tbody>
  </table>

  <legend><p class="sale-info lead">Sales Data</p></legend>

  <% unless @reports.nil? %>

    <%= render "months_table" %>
    <legend></legend>

  <% end %>

</div>
</div>